### ISSUE TITLE
AuthorizedKeysCommand-like possibility.

### ISSUE THREAD

**Issue by LaKing** [tg123/sshpiper#10]
GREAT stuff you have here. I'm very happy that I found it.

Standard SSH has AuthorizedKeysCommand / AuthorizedKeysCommandUser configuration directive that basiclly allows scripts to return the authorizedkeys string. 

I'm wondering if it would be possible to implement such a behaviour into sshpiperd, so that authorisation can be dynamic or scripted. ...

Thank you! .)

**Comment by tg123** [comment]
An non-opensource version that supports lua script was abandoned long ago.
I will rewrite the feature and open it later.

SSH Piper contains two parts: enhanced golang/x/ssh, which adds pipe support and sshpiperd which make sshpiper a daemon and a cli.
You can build your own sshpiperd if you cannot wait.

you can find exmaples on godoc

**Comment by LaKing** [comment]
I managed to modify the workingdir.go file according my needs. 

Thank you. :1st_place_medal:
