### ISSUE TITLE
Missing plugins on the docker image

### ISSUE THREAD

**Issue by paolomainardi** [tg123/sshpiper#101]
Hi! I am not sure i am using it in the right way, but I tried to use the yaml plugin without success and finally I discovered that the plugin seems to be missing in the docker image:

```shell
❯ docker run --rm -it farmer1992/sshpiperd:latest ls /sshpiperd/plugins/
kubernetes  workingdir
```

Only `kubernetes`and `workingdir` are present.

Is it something known ?

**Comment by tg123** [comment]
you can use `farmer1992/sshpiperd:v1.0.50` as a workaround

I am trimming image to smaller size and reducing build time (5h+), still planning which image tag to put all plugins

**Comment by paolomainardi** [comment]
ok thanks @tg123

**Comment by paolomainardi** [comment]
ok thanks @tg123

**Comment by tg123** [comment]
#125
now all plugins can be found in `full-vx.x.x.x`

**Comment by paolomainardi** [comment]
Thanks 🙏
