### ISSUE TITLE
Public Key Auth fails with MacOS Ventura

### ISSUE THREAD

**Issue by developedsoftware** [tg123/sshpiper#110]
https://superuser.com/questions/1749364/git-ssh-permission-denied-in-macos-13-ventura

I am using v0 of the software (v1 doesnt work for our needs at the moment)

Would you expect OpenSSL issues with Ventura? 

> macOS 13 (Ventura) ships with OpenSSH_9.0p1. According to the OpenSSH release notes:
> 
> This release disables RSA signatures using the SHA-1 hash algorithm by default. This change has been made as the SHA-1 hash algorithm is cryptographically broken, and it is possible to create chosen-prefix hash collisions for <USD$50K [1]
> 

Is there any way of fixing it? I assume its something to do with the key exchange (man in the middle) 

The same key under Ventura seems to work on other servers (linux out of the box). But it fails on sshpiper.

**Comment by tg123** [comment]
sshpiper supports ed25519
you can set with `-i `


I will make sshpiper default key to ed25519

**Comment by tg123** [comment]
sshpiperd -i /path/to/ssh_host_ed25519_key

**Comment by developedsoftware** [comment]
Thanks, can you confirm this will work in v0.7.42 (I appreciate its 6 months old)

**Comment by developedsoftware** [comment]
Can the path to the ed25519_key be set in the sshd_config like every other parameter?

**Comment by tg123** [comment]
you do not have to change anything in sshd as it is behind the sshpiper
ssh will not know what algo sshd is using

**Comment by tg123** [comment]
the sshpiper by default is using rsa which is deprecated in newer openssh client (>8.6 maybe)

**Comment by developedsoftware** [comment]
Thanks. For anybody else I got this working again in Docker by changing 

`-v /etc/ssh/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key`

to 

```
--volume /etc/ssh/ssh_host_rsa_key:/etc/ssh/ssh_host_dsa_key:ro \
--volume /etc/ssh/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key:ro \
--volume /etc/ssh/ssh_host_ecdsa_key:/etc/ssh/ssh_host_ecdsa_key:ro \
--volume /etc/ssh/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key:ro \
```

And SSHPiper started working again. 

Do you want me to close this issue or keep it open until the fix is implemented?
