### ISSUE TITLE
Documentation needed: building plugins

### ISSUE THREAD

**Issue by mjbright** [tg123/sshpiper#114]
I just followed the instructions to build sshpiper, worked nicely once I upgraded my go version.
However, it isn't stated how to build individual, or all, plugins.

Please add information on how to build sshpiper along with all plugins.

After, building sshpiper, as described in the README, I have just 3 plugins in ./out/:
```
$ ll out/
total 74016
drwxrwxr-x  2 mjb mjb     4096 Dec 23 10:49 ./
drwxrwxr-x 10 mjb mjb     4096 Dec 23 10:48 ../
-rwxrwxr-x  1 mjb mjb 46244636 Dec 23 10:49 kubernetes*
-rwxrwxr-x  1 mjb mjb 15645256 Dec 23 10:49 sshpiperd*
-rwxrwxr-x  1 mjb mjb 13889351 Dec 23 10:49 workingdir*
```

I tried to build the simplemath plugin for example:
```
$ cd plugin/simplemath/
$ go build
package github.com/tg123/sshpiper/plugin/simplemath: build constraints exclude all Go files in /home/mjb/src/github.com/tg123.sshpiper/plugin/simplemath
```

**Comment by tg123** [comment]
hmm it is confusing after i trimmed the docker image, I will update the doc

you have to build with `go build -tags full` atm
