### ISSUE TITLE
Is every docker container accessible?

### ISSUE THREAD

**Issue by nik736** [tg123/sshpiper#133]
Hi there! Thanks for this project. I have two questions. 

I am using sshpiperd with the docker plugin. With the example openssh-server image everything is working fine. When using other images I am getting `dial tcp 172.17.0.3:2222: connect: connection refused `. I guess because those images do not have a SSH deamon installed. The container is accessible via regular `docker exec -ti bash` command though. Is this expected behaviour? Or is there something else wrong.

My use case is to have several users and each user will access a docker container. Users and containers should be changed on the fly so my second question would be if it is possible to use sshpiper for this use-case? I think I need the yaml config with docker, is this possible? Are there any examples for this?

Thanks a lot for your time! :)

**Comment by shiipou** [comment]
You need to have an SSH server running in your docker image.

**Comment by tg123** [comment]
Yup 

sshpiper `pipes` ssh servers

but you can check another project of mine
https://github.com/tg123/docker-sshd

it converts any docker instance to ssh server, no sshd needed
