### ISSUE TITLE
How to use keys in docker plug-ins

### ISSUE THREAD

**Issue by sinbino** [tg123/sshpiper#136]
No matter how I set sshpiper.authorized_keys and sshpiper.private_key, the following error is returned.
```
cannot create upstream for 192.168.xxx.xxx:xxxxx with public key auth: rpc error: code = Unknown desc = ssh: no key found
```
With password authentication, I am able to connect with the same settings by simply removing sshpiper.authorized_keys and sshpiper.private_key from the container.

Please could you give me some advice on how to set up the use of authentication keys?

**Comment by sinbino** [comment]
Resolved.
It worked by base64 encoding the authorized_keys and id_ed25519 files as is.

**Comment by tg123** [comment]
hmm the param name is bit confusing, should be xx-base64 for better accuracy

**Comment by sinbino** [comment]
Alternatively, it would be easier to understand by simply adding a simple sample to the plugin's README.md.
