### ISSUE TITLE
pam does not work with sshpiper

### ISSUE THREAD

**Issue by bdh3** [tg123/sshpiper#15]
I am currently working on using sshpiper.
The pam function does not work and we will contact you.

#1. #################################################
## /etc/sshpiperd.ini 

[sshpiperd]
listen-address = 0.0.0.0
listen-port = 2222
server-key = /etc/ssh/ssh_host_rsa_key
upstream-driver = workingdir
challenger-driver = pam
auditor-driver = typescript-logger
log-path =
log-flags = 3

[upstream.mysql]
upstream-mysql-host = 127.0.0.1
upstream-mysql-user = sshpiper
upstream-mysql-password = sshpiper
upstream-mysql-port = 3306
upstream-mysql-dbname = sshpiper

[upstream.workingdir]
workingdir = /var/sshpiper
workingdir-allowbadusername = false
workingdir-nocheckperm = false

[challenger.welcometext]
challenger-welcometext =

[auditor.typescript-logger]
auditor-typescriptlogger-outputdir = /var/sshpiper

#2. ##########################################################
## /etc/pam.d/sshpiperd 
#%PAM-1.0
#auth required pam_access.so
account required pam_access.so

#3. ##########################################################
## result 

2018/10/17 02:45:35 connection accepted: 10.11.1.100:10246
panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 6 [running]:
github.com/tg123/sshpiper/vendor/github.com/vvanpo/golang-pam.newConversation.func1(0xc4201a6360, 0xc4201a6360)
        /go/src/github.com/tg123/sshpiper/vendor/github.com/vvanpo/golang-pam/pam.go:43 +0x48
github.com/tg123/sshpiper/vendor/github.com/vvanpo/golang-pam.newConversation(0x8560e0, 0xc4201a6340, 0xc42004abc0)
        /go/src/github.com/tg123/sshpiper/vendor/github.com/vvanpo/golang-pam/pam.go:43 +0x63
github.com/tg123/sshpiper/vendor/github.com/vvanpo/golang-pam.Start(0x80fcb8, 0x9, 0xc42017e078, 0x4, 0x8560e0, 0xc4201a6340, 0xc4201aa080, 0x0)
        /go/src/github.com/tg123/sshpiper/vendor/github.com/vvanpo/golang-pam/pam.go:78 +0x53
github.com/tg123/sshpiper/sshpiperd/challenger/pam.pamChallenger(0x85a120, 0xc42018c008, 0xc4201aa080, 0x0, 0x0, 0x0)
        /go/src/github.com/tg123/sshpiper/sshpiperd/challenger/pam/pam_challenger.go:40 +0x1c1
github.com/tg123/sshpiper/vendor/golang.org/x/crypto/ssh.NewSSHPiperConn(0x85a600, 0xc42000e208, 0xc42009cb40, 0x0, 0x0, 0x0)
        /go/src/github.com/tg123/sshpiper/vendor/golang.org/x/crypto/ssh/sshpiper.go:216 +0x41a
main.startPiper.func1(0x85a600, 0xc42000e208, 0xc42009cb40, 0xc420094550, 0x859120, 0xc420010f50)
        /go/src/github.com/tg123/sshpiper/sshpiperd/sshpiperd.go:151 +0x5a
created by main.startPiper
        /go/src/github.com/tg123/sshpiper/sshpiperd/sshpiperd.go:150 +0x447
############################################################

Please ask for help.
Thank you.

**Comment by tg123** [comment]
cloud you please provide more info about your pam settings?

**Comment by bdh3** [comment]
thank you for answering. i'm refer to /etc/pam.d/sshd and /etc/pam.d/login.

# into /etc/pam.d/sshpiperd 
#%PAM-1.0
auth [user_unknown=ignore success=ok ignore=ignore default=bad] pam_securetty.so
auth       substack     system-auth
auth       include      postlogin
account    required     pam_nologin.so
account    include      system-auth
account    required     pam_access.so
password   include      system-auth
# pam_selinux.so close should be the first session rule
session    required     pam_selinux.so close
session    required     pam_loginuid.so
session    optional     pam_console.so
# pam_selinux.so open should only be followed by sessions to be executed in the user context
session    required     pam_selinux.so open
session    required     pam_namespace.so
session    optional     pam_keyinit.so force revoke
session    include      system-auth
session    include      postlogin
-session   optional     pam_ck_connector.so


It seems to work when applied to sshd rather than sshpiper.

**Comment by tg123** [comment]
golang pam module panic
any system info please

I will try to repo

**Comment by bdh3** [comment]
- OS version
CentOS 7.5
kernel 3.10.0-862.11.6.el7.x86_64

- Docker version
18.06.1-ce

- sshpiperd version
Version       : v0.4dev
Go  Runtime   : go1.10
Git Commit    : 3243906,2018-02-25

The same is true for testing with the sshpiper daemon, not the container.
It would be great if it solved. Thank.

**Comment by bdh3** [comment]
- OS version
CentOS 7.5
kernel 3.10.0-862.11.6.el7.x86_64

- Docker version
18.06.1-ce

- sshpiperd version
Version       : v0.4dev
Go  Runtime   : go1.10
Git Commit    : 3243906,2018-02-25

The same is true for testing with the sshpiper daemon, not the container.
It would be great if it solved. Thank.

**Comment by bdh3** [comment]
- OS version
CentOS 7.5
kernel 3.10.0-862.11.6.el7.x86_64

- Docker version
18.06.1-ce

- sshpiperd version
Version       : v0.4dev
Go  Runtime   : go1.10
Git Commit    : 3243906,2018-02-25

The same is true for testing with the sshpiper daemon, not the container.
It would be great if it solved. Thank.

**Comment by tg123** [comment]
update lib pam 7ab78cc

**Comment by tg123** [comment]
verified on deb9  and ubuntu 1804
