### ISSUE TITLE
Unable to use git repos behind sshpiper

### ISSUE THREAD

**Issue by r2DoesInc** [tg123/sshpiper#156]
This may not be one of the use cases for the project, but I was hoping to put my git repos behind the sshpiper proxy as well. I got close, I have my matching keys, but when attempting to clone a repo, sshpiper spams the logs with linnes similar to

> May 24 23:37:14 gateway start_ssh_piper.sh[1204]: time="2023-05-24T23:37:14Z" level=info msg="found mapping key /var/sshpiper/git/id_rsa"
> May 24 23:37:14 gateway start_ssh_piper.sh[1204]: message repeated 17 times: [ time="2023-05-24T23:37:14Z" level=info msg="found mapping key /var/sshpiper/git/id_rsa"]
> May 24 23:37:15 gateway start_ssh_piper.sh[1204]: time="2023-05-24T23:37:15Z" level=info msg="found mapping key /var/sshpiper/git/id_rsa"
> May 24 23:37:15 gateway start_ssh_piper.sh[1204]: message repeated 17 times: [ time="2023-05-24T23:37:15Z" level=info msg="found mapping key /var/sshpiper/git/id_rsa"]
> May 24 23:37:16 gateway start_ssh_piper.sh[1204]: time="2023-05-24T23:37:16Z" level=info msg="found mapping key /var/sshpiper/git/id_rsa"
> May 24 23:37:16 gateway start_ssh_piper.sh[1204]: message repeated 16 times: [ time="2023-05-24T23:37:16Z" level=info msg="found mapping key /var/sshpiper/git/id_rsa"]
> May 24 23:37:17 gateway start_ssh_piper.sh[1204]: time="2023-05-24T23:37:17Z" level=info msg="found mapping key /var/sshpiper/git/id_rsa"
> May 24 23:37:17 gateway start_ssh_piper.sh[1204]: message repeated 17 times: [ time="2023-05-24T23:37:17Z" level=info msg="found mapping key /var/sshpiper/git/id_rsa"]
> May 24 23:37:18 gateway start_ssh_piper.sh[1204]: time="2023-05-24T23:37:18Z" level=info msg="found mapping key /var/sshpiper/git/id_rsa"
> May 24 23:37:18 gateway start_ssh_piper.sh[1204]: message repeated 17 times: [ time="2023-05-24T23:37:18Z" level=info msg="found mapping key /var/sshpiper/git/id_rsa"]
> May 24 23:37:19 gateway start_ssh_piper.sh[1204]: time="2023-05-24T23:37:19Z" level=info msg="found mapping key /var/sshpiper/git/id_rsa"
> May 24 23:37:19 gateway start_ssh_piper.sh[1204]: message repeated 16 times: [ time="2023-05-24T23:37:19Z" level=info msg="found mapping key /var/sshpiper/git/id_rsa"]
> May 24 23:37:20 gateway start_ssh_piper.sh[1204]: time="2023-05-24T23:37:20Z" level=info msg="found mapping key /var/sshpiper/git/id_rsa"
> May 24 23:37:20 gateway start_ssh_piper.sh[1204]: message repeated 16 times: [ time="2023-05-24T23:37:20Z" level=info msg="found mapping key /var/sshpiper/git/id_rsa"]
> May 24 23:37:21 gateway start_ssh_piper.sh[1204]: time="2023-05-24T23:37:21Z" level=info msg="found mapping key /var/sshpiper/git/id_rsa"
> May 24 23:37:21 gateway start_ssh_piper.sh[1204]: message repeated 17 times: [ time="2023-05-24T23:37:21Z" level=info msg="found mapping key /var/sshpiper/git/id_rsa"]
> May 24 23:37:22 gateway start_ssh_piper.sh[1204]: time="2023-05-24T23:37:22Z" level=info msg="found mapping key /var/sshpiper/git/id_rsa"

testing git via thje `-T` flag also does not work, it just prints the same key found message as above and hangs until the connection ends.

**Comment by tg123** [comment]
likely the client was retrying to connect
could you please double confirm if your `/var/sshpiper/git/id_rsa` is enable to connect to your `upstream`?
