### ISSUE TITLE
Built-in automatic blocklist

### ISSUE THREAD

**Issue by vholer** [tg123/sshpiper#157]
It would be nice if it's possible to configure sshpiper to apply some IP-based restrictions on clients after a number of failed attempts. Similar functionality is usually provided by tools like fail2ban / denyhosts, but in Kubernetes envs. it's not that easy to use these. 

Possible options:
- max. number of failed attempts,
- timeframe,
- ban time,
- always allowed / blocked ranges

Successful login resets the counter. Persistence of state across restarts is not IMHO importatnt.

**Comment by tg123** [comment]
maybe bake fail2ban into image?

**Comment by vholer** [comment]
Related draft to discuss https://github.com/tg123/sshpiper/pull/158.

**Comment by tg123** [comment]
https://github.com/tg123/sshpiper/tree/master/plugin/failtoban
