### ISSUE TITLE
Default backend upstream.

### ISSUE THREAD

**Issue by grzsmp** [tg123/sshpiper#16]
Hi! Great work!
But what about supporting default backend upstream if user didn't match?
This is very usefull feature for example in case of migration users from one servers to another.
For example migrated users are mapped to new server, and everyone else (no mapped) to old (default) server.
Right now I just replaced the query:
--- a/sshpiperd/upstream/mysql/crud/user_upstream_map.go
+++ b/sshpiperd/upstream/mysql/crud/user_upstream_map.go
@@ -161,7 +161,7 @@ func (t *UserUpstreamMap) GetByUpstreamId(UpstreamId int64) ([]*UserUpstreamMapR
 }
 
 func (t *UserUpstreamMap) GetByUsername(Username string) ([]*UserUpstreamMapRecord, error) {
-       r, err := t.db.Query("select * from user_upstream_map where username=?", Username)
+       r, err := t.db.Query("select * from user_upstream_map where id = (select ifnull((select id from user_upstream_map where username=?), (select id from user_upstream_map where username='default')))", Username)
        if err != nil {
                return nil, err
        }

**Comment by tg123** [comment]
cloud you please have a look at branch reforage_mysql
going to replace driver to gorm

**Comment by tg123** [comment]
added to `working dir` driver

**Comment by tg123** [comment]
database supported

add `FALLBACK_USER` in config table
