### ISSUE TITLE
Show current upstream config?

### ISSUE THREAD

**Issue by pwFoo** [tg123/sshpiper#164]
Hi,
I would use sshpiper with docker (swarm). Used an older sshpiper with workdir before. So all configs found in the filesystem. Is it possible to show all configured upstreams by command or filesystem?

**Comment by pwFoo** [comment]
I started the new container with docker plugin. Can't find a workingdir used to save the docker upstreams?

**Comment by tg123** [comment]
docker plugin does not use any dir
it use container label https://github.com/tg123/sshpiper/tree/master/plugin/docker#container-labels-for-plugin

**Comment by pwFoo** [comment]
HI @tg123 ,
I know the container labels. And how to show a list of configured (by labels) upstreams :)

**Comment by pwFoo** [comment]
Sorry, I think we talk about different things?
Not list compose / docker labels, output current sshpiperd configuration of upstreams to verify if all containers added to sshpiper.

**Comment by tg123** [comment]
docker plugin loads running containers every time when a client is attempting to connect
so you can just ensure container does have labels

if you really want to list them
maybe add a log to dump pipes here
https://github.com/tg123/sshpiper/blob/72fc5488af306af9a26ed216db7a28e9c216a2c7/plugin/docker/docker.go#L178
