### ISSUE TITLE
How to check if the password is wrong or sshd server is not ready

### ISSUE THREAD

**Issue by 1534854467** [tg123/sshpiper#166]
got "Permission denied(password)" when I use the wrong password or the sshd does not start.

how to check if the password is wrong or sshd server is not ready?

![not-ready](https://github.com/tg123/sshpiper/assets/9970182/76ecf414-604a-4f3f-b54c-7d27e739f6b6)

**Comment by tg123** [comment]
you can check sshpiperd logs for the reason of failed attempts

**Comment by 1534854467** [comment]
> you can check sshpiperd logs for the reason of failed attempts

has any way check by the ssh return information?

**Comment by tg123** [comment]
for example, you will see `dial tcp 127.0.0.1:23: connect: connection refused ` if remote is not available 

```
ERRO[0019] cannot create upstream for 127.0.0.1:58014 (username [root]) with password auth: dial tcp 127.0.0.1:23: connect: connection refused 
```

**Comment by 1534854467** [comment]
yes, i see this error message in the sshpiperd server when upstream connection  refused 

but ssh client still show "Permission denied  (password)"

if i was a user, i don't know if my sshd server is running by terminal print

**Comment by tg123** [comment]
sshpiper will not know the upstream endpoint until the downstream (user) entered password.
and the upstream may be different if the password not the same.

also, there is no way to send an error/msg to downstream side during ssh password auth.

**Comment by 1534854467** [comment]
[https://github.com/tg123/sshpiper.crypto/pull/2](url)

@tg123 
please review this pr

**Comment by tg123** [comment]
basically, should not touch any file in original crypto. all change should be limited to sshpiper.go
you should add hook in your case.
`UpstreamAuthFailureCallback`

but now there is now way to write back to client side

**Comment by 1534854467** [comment]
https://github.com/tg123/sshpiper.crypto/pull/3

@tg123 
I have a new pr, please review it again

**Comment by tg123** [comment]
IHMO, this introduces some security concern that `downstream` can detected if user is valid or not

however, i am happy if it can be customized via plugin

some changes in crypto in my mind

in `authUpstream` add a new DisconnectErr handler
if DisconnectErr { send DisconnectErr  msg }

the DisconnectErr is returned by `NextAuthMethods` after `UpstreamAuthFailureCallback` noticed some special err
everything should be done in plugin


you can check `failtoban` to see if it is good enough for your case after new API added

**Comment by tg123** [comment]
user name is only available after first handshake, you can do health check in PasswordCallback for exmaple, return err to disconnect
