### ISSUE TITLE
installation with pam support fails

### ISSUE THREAD

**Issue by csazku** [tg123/sshpiper#18]
When I run the go get command i get the following error:

# github.com/tg123/sshpiper/vendor/github.com/vvanpo/golang-pam
In file included from go/src/github.com/tg123/sshpiper/vendor/github.com/vvanpo/golang-pam/pam.go:6:0:
./golang-pam.h:1:31: fatal error: security/pam_appl.h: No such file or directory
compilation terminated.

**Comment by tg123** [comment]
typically, you need to have `libpam` something in your linux distribution
you can check `Dockerfile` for an example. it installs libpam on deb
