### ISSUE TITLE
Kubernetes field annotations have lowest priority

### ISSUE THREAD

**Issue by vholer** [tg123/sshpiper#214]
During the search for data in Kubernetes secrets, multiple key name options are evaluated including a custom name taken from the annotation. The annotation is evaluated only as a very last option if common key names are not found. This doesn't give the user option to override the actual key name. E.g.,

https://github.com/tg123/sshpiper/blob/694d09affda529c18f33210959bb1732a61a8e59/plugin/kubernetes/kubernetes.go#L161

IMHO, the annotation should be evaluated first before `ssh-privatekey` or `privatekey`. Applies also for other Secret attributes:

```plugin/kubernetes/kubernetes.go
161:		for _, k := range []string{"ssh-privatekey", "privatekey", anno["privatekey_field_name"]} {
170:		for _, k := range []string{"ssh-publickey", "publickey", anno["publickey_field_name"]} {
192:		for _, k := range []string{"password", anno["password_field_name"]} {
```

**Comment by tg123** [comment]
hmmm yup you're right 
lets fix it

i will do it at the weekend 
or your PR is welcomed
