### ISSUE TITLE
Debugging Connection

### ISSUE THREAD

**Issue by sean-e-dietrich** [tg123/sshpiper#25]
Is there a way to debug the connection details?

I am trying to set up sshpiper to be the main point of contact to enter in docker. Specifically using have the working directory set up as the docker compose project name.

`/etc/sshpiperd.ini`

```
[sshpiperd]
listen = 0.0.0.0
port = 2222
server-key = /etc/ssh/ssh_host_rsa_key
upstream-driver = workingdir
challenger-driver =
auditor-driver =
banner-text =
banner-file = /banner.txt
log =
log-flags = 3

[upstream.workingdir]
upstream-workingdir = /var/sshpiper
upstream-workingdir-allowbadusername = false
upstream-workingdir-nocheckperm = false
upstream-workingdir-fallbackusername =
upstream-workingdir-stricthostkey = false
```

And the directory structure looks like this

Directory is `/var/sshpiper/[PROJECT NAME]`

And the directory looks like this

```
/var/sshpiper/pantheon-site # ls -lah
total 20
drwxr-xr-x    2 root     root        4.0K Jan 21 19:08 .
drwxr-xr-x    4 root     root        4.0K Jan 21 19:04 ..
-r--------    1 root     root         429 Jan 21 19:04 authorized_keys
-r--------    1 root     root        3.2K Jan 21 19:05 id_rsa
-r--------    1 root     root          44 Jan 21 19:17 sshpiper_upstream
```

and `sshpiper_upstream` looks like

```
/var/sshpiper/pantheon-site # cat sshpiper_upstream
ssh docker@pantheon-site_cli_1_be91bc655ad4
```

But when running the following command:

```
ssh -i [KEY] -vvv [IP] -p 2222 -l pantheon-site
```

I am asked for a password. I have added my ssh key to the `authorized_keys` file on the sshpiper container. The key `/var/sshpiper/pantheon-site/id_rsa` has been added to the `pantheon-site_cli_1_be91bc655ad4` container. And the sshpiper container has been added to the same network as the `pantheon-site` project.

Is there something else I am missing?

**Comment by sean-e-dietrich** [comment]
Disregard this as I found what I was doing wrong. I thought the `sshpiper_upstream` should contain the word `ssh` but it shouldn't. So removed it and tried again and everything was all set.

**Comment by tg123** [comment]
you can use `sshpiperd pipe add/list` to manage them now
more tools such as key management is under development.
