### ISSUE TITLE
rest upstream

### ISSUE THREAD

**Issue by kfox1111** [tg123/sshpiper#28]
I would like to integrate sshpiper with some other systems. While it could be done via the database upstream plugin, it would cause for more maintenance then required to store and sync the extra state.

What would be most useful is if there was an upstream that supported a rest api (authenticated with basic auth) that could deal with all the plugin logic. Then glue could easily be written in that rest api to allow it to talk to other systems that may already have their own state. (stateless glue). Thus simplifying the overall implementation greatly. It could also enhance security as the rest api could have permissions to do things that you wouln't want your internet facing ssh service to be able to do.

**Comment by tg123** [comment]
good idea, 

backlog in v0.5

**Comment by ahoeg** [comment]
Rest API would make generation easier.
At the moment I generate on file base with an older sshpiper version with a additional docker-gen container.

Would be great to use docker labels to generate the servers / pipes? Maybe with an additional docker-gen container and rest requests to sshpiper...

**Comment by ahoeg** [comment]
Rest API would make generation easier.
At the moment I generate on file base with an older sshpiper version with a additional docker-gen container.

Would be great to use docker labels to generate the servers / pipes? Maybe with an additional docker-gen container and rest requests to sshpiper...

**Comment by tg123** [comment]
grpc upstream added
