### ISSUE TITLE
add flag `--kubeconfig` for kubernetes plugin

### ISSUE THREAD

**Issue by haiker2011** [tg123/sshpiper#295]
some time we may need use external kubeconfig to init k8s client, now kubernetes plugin only support default kubeConfig

**Comment by tg123** [comment]
env var `KUBECONFIG` is supported
but i agree to add `--kubeconfig`, seems there was already an option in sdk

**Comment by haiker2011** [comment]
@tg123 I am not found env var KUBECONFIG in doc and code, so i add this issue

**Comment by tg123** [comment]
from k8s sdk, the plugin uses it to load kubeconfig
https://github.com/kubernetes/client-go/blob/v0.29.0/tools/clientcmd/loader.go#L160
