### ISSUE TITLE
Pass agent?

### ISSUE THREAD

**Issue by digitalsparky** [tg123/sshpiper#30]
Hi, just wondering, If at all possible, it'd be nice to be able to accept and pass a forwarded agent instead of having to use internal id_rsa keys.

This can be useful on systems that use their keys to identify users, such as gitlab, where all users connect to the 'git' users, and the script identifies them by key.

Otherwise in this instance there would have to be double the amount of keys generated.

Cheers!

Matt

**Comment by tg123** [comment]
short answer is no
the reason is that the protocol prevents `man-in-the-middle` from happening

details:
https://github.com/tg123/sshpiper#how-to-do-public-key-authentication-when-using-sshpiper
