### ISSUE TITLE
Allow dot character as part of a user name

### ISSUE THREAD

**Issue by windware** [tg123/sshpiper#31]
It seems your regexp to check for a valid user name in `usernameRule` doesn't allow for a dot, but it's a valid character for a unix user name.

`^[a-z_][-a-z0-9_]{0,31}$`

**Comment by tg123** [comment]
discussion #9 
or it can be disable by `--upstream-workingdir-allowbadusernam`

**Comment by windware** [comment]
No, I don't want to allow that config when you mention it as a security precaution.
Added on #9.
