### ISSUE TITLE
Can not login with ssh-key

### ISSUE THREAD

**Issue by petershaw** [tg123/sshpiper#33]
Hi, 
very cool tool. It works with passwords very well. But I have issues with keys:
I generate new keys and store them to the user folder, on the target host, I copied the key to authorised_keys file. I can connect to the target host with the key from inside the sshpiper container. But from outside i've got this in the logs: 

```
connection accepted: *.*.*.*:60983
2019/06/14 16:41:42 mapping user [****] to [@172.20.0.1:2222]
2019/06/14 16:41:42 mapping private key error: ssh: no key found, public key auth denied for [****] from [*.*.*.*:60983]
```

This is my layout from the users folder: 
```
drwxr-xr-x 2 me root 4096 Jun 14 18:29 .
drwxrwxr-x 6 root dobo 4096 Jun 14 18:09 ..
-rw------- 1 me root  748 Jun 14 17:14 authorized_keys
-rw------- 1 me my 1675 Jun 14 18:32 id_rsa
-rw-r--r-- 1 me my  406 Jun 14 18:32 id_rsa.pub
-rw------- 1 root root   16 Jun 14 17:12 sshpiper_upstream
```

Again, password works like a charm. but I can't find out why the keys aren't found. 

Thanks for help. 
ps

**Comment by tg123** [comment]
please check your id_rsa and authorized_keys format
authorized_keys: `OpenSSH format`
id_rsa: `supports RSA (PKCS#1), PKCS#8, DSA (OpenSSL), and ECDSA private keys`

bad format might cause `no key found`

**Comment by tg123** [comment]
Reopen if still it is not working

**Comment by petershaw** [comment]
Thanks a lot!
