### ISSUE TITLE
[Feature request] Package for OpenWRT

### ISSUE THREAD

**Issue by callumgare** [tg123/sshpiper#345]
## Summary
Create an [OpenWRT package](https://openwrt.org/docs/guide-developer/packages) of sshpiper so it can be run on a router running OpenWRT

## More info
I completely understand if you decide to close this ticket as “out of scope” or “not planned” but I’d love to be able to run sshpiper directly on my home router. That way when I’m away from home I could ssh my home ip and have sshpiper forward the connection different devices. I currently have my router port forward 22 to a particular computer and then that computer runs sshpiper and forwards to other computers but it would be great to just run sshpiper directly on the router.

Thanks for your consideration and very useful piece of software!

**Comment by tg123** [comment]
more than happy to support openwrt, seems adding a go based app is not too hard
but i am new to openwrt, let me dig it 


btw pr is welcomed.

**Comment by ihidchaos** [comment]
Hi everyone,
I have written a package for the OpenWrt platform, please help verify that it meets your needs. See [sshpiper-openwrt](https://github.com/ihidchaos/sshpiper-openwrt).

At present, the sdk of the [mt76x8](https://downloads.openwrt.org/snapshots/targets/ramips/mt76x8/) platform I use has been successfully compiled. If you need to verify on a specific platform and architecture, I can compile the corresponding software package for you.

**Comment by callumgare** [comment]
Oh fantastic! Thanks both!

@ihidchaos Can I take you up on that offer to build a package for specific platform?  My router is the uses the `ipq806x/generic` target platform?

**Comment by ihidchaos** [comment]
> Oh fantastic! Thanks both!
> 
> @ihidchaos Can I take you up on that offer to build a package for specific platform? My router is the uses the `ipq806x/generic` target platform?

Of course, please try this package. Since I don't know your OpenWrt distribution version(21.02 or 19.07 or older), I used the [latest](https://downloads.openwrt.org/snapshots/targets/ipq806x/generic/) version of the SDK to compile. Note that the ipk package is inside the zip package.
[sshpiper_1.2.8-r1_arm_cortex-a15_neon-vfpv4.zip](https://github.com/tg123/sshpiper/files/14768338/sshpiper_1.2.8-r1_arm_cortex-a15_neon-vfpv4.zip)

**Comment by callumgare** [comment]
Thanks! I'm on 23.05.0 so using latest seemed to work. Got it installed and I've worked out I have to set the env var `SSHPIPERD_SERVER_KEY` to `/etc/dropbear/dropbear_ed25519_host_key` however I'm not sure how to solve the error message `ssh: no key found`. This is what I'm getting:

```
root@router:/tmp# env SSHPIPERD_SERVER_KEY=/etc/dropbear/dropbear_ed25519_host_key sshpiperd workingdirbykey --root /etc/sshpiper
INFO[0000] starting sshpiperd version: (devel), go1.21.4
INFO[0000] found host keys [/etc/dropbear/dropbear_ed25519_host_key]
INFO[0000] loading host key /etc/dropbear/dropbear_ed25519_host_key
FATA[0000] ssh: no key found
```

**Comment by tg123** [comment]
use `SSHPIPERD_SERVER_KEY_GENERATE_MODE` to generate one?

please copy the key file and verify with sshd

**Comment by callumgare** [comment]
@tg123 Thanks for that :) Sorry I'm only just replying now.

I've now tried setting that using `env SSHPIPERD_SERVER_KEY_GENERATE_MODE=notexist SSHPIPERD_SERVER_KEY=/etc/dropbear/dropbear_ed25519_host_key sshpiperd workingdirbykey --root /etc/sshpiper` as well as setting the option using the command line argument (`env SSHPIPERD_SERVER_KEY=/etc/dropbear/dropbear_ed25519_host_key sshpiperd workingdirbykey --root /etc/sshpiper --server-key-generate-mode notexist`). Unfortunately I'm still getting the same output as before and I'm not seeing any key generated in /env/sshpiper (I assume that's where it would be placed). I've also tried the value "always" instead of "notexist" but there's not difference.

**Comment by tg123** [comment]
try to rebuild openwrt, workingdirbykey is now merged into workingdir
