### ISSUE TITLE
[Feature request] Include other first-party plugins in the offical docker image

### ISSUE THREAD

**Issue by callumgare** [tg123/sshpiper#347]
At the moment the docker image available at https://hub.docker.com/r/farmer1992/sshpiperd only includes the `kubernetes` and `workingdir` plugins (`docker run --rm --entrypoint sh farmer1992/sshpiperd:latest -c 'ls /sshpiperd/plugins'`). For convenience it would be great if the image included all plugins in  https://github.com/tg123/sshpiper/tree/master/plugin (and if there are any particularly popular third-party plugins maybe some of those too).

Thanks!

**Comment by callumgare** [comment]
Ahh! Reading though https://github.com/tg123/sshpiper/blob/ffcf6ac0ad99657313d8f24854149b778a9db9c0/.goreleaser.yaml I can see there's a second image released under the tag "full" which includes all the plugins. If the `latest` tag is only meant to have a small number of plugins it might be a good idea to document that in the README.md and the docker hub page description (https://hub.docker.com/r/farmer1992/sshpiperd)

**Comment by callumgare** [comment]
Ah, looks like the `full` tag is still missing some plugins. Specifically the `workingdirbykey` which is the one I'm wanting to use: `docker run --rm --entrypoint sh farmer1992/sshpiperd:full -c 'ls -hal /sshpiperd/plugins'`

**Comment by tg123** [comment]
yes correct, full tag has everything in it

**Comment by callumgare** [comment]
@tg123 It looks like full might still be missing some plugins. Running `docker run --rm --entrypoint sh farmer1992/sshpiperd:full -c 'ls -hal /sshpiperd/plugins'` shows me `docker`, `failtoban`, `fixed`, `kubernetes`, `workingdir`, and `yaml` so it seems to be missing `azdevicecode`, `simplemath`, `testcaplugin` (although I'm guessing this is just for testing so it doesn't matter if it's in the docker image or not), `testplugin` (same I presume), `totp` and `workingdirbykey` (which is the plugin I'd like to use).

**Comment by tg123** [comment]
ah i see, let me add them this weekend

btw, you can also send a pr to update build tag for those plugins to have them in `full`

**Comment by tg123** [comment]
#348

**Comment by callumgare** [comment]
@tg123 Just a heads up, it seems like this might still be not fixed. Running `docker pull farmer1992/sshpiperd:full` (to make sure I have the latest image) then running `docker run --rm --entrypoint sh farmer1992/sshpiperd:full -c 'ls /sshpiperd/plugins'` again lists 6 plugins: docker, failtoban, fixed, kubernetes, workingdir and yaml. "workingdirbykey" (the plugin I'm interested in using) + a few others still appears to be missing.

**Comment by tg123** [comment]
merged into workingdir
see [Recursive mode](https://github.com/tg123/sshpiper/tree/master/plugin/workingdir#recursive-mode---recursive-search)
