### ISSUE TITLE
Configure cryptography parameters for downstream side

### ISSUE THREAD

**Issue by Nils98Ar** [tg123/sshpiper#354]
Is this possible somehow? E.g. restricting the allowed cryptography algorithms.

It would also be okay to build a new image from source or from base image.

**Comment by tg123** [comment]
no cmd settings now
but if you prefer compile yourself, you can set it here

https://github.com/tg123/sshpiper/blob/c83c27cb48489ac0c0552c05ee4da2369d6075c7/cmd/sshpiperd/daemon.go#L183
```
d.config.PiperConfig.PublicKeyAuthAlgorithms
```


PR is welcomed

**Comment by Nils98Ar** [comment]
@tg123 

I have never worked with go before but I think it would be good to configure this via config file and environment variables?

This seems to be the default?
https://github.com/golang/crypto/blob/v0.21.0/ssh/common.go#L142-L148

**Comment by Nils98Ar** [comment]
These are also interesting regarding security: `supportedCiphers`, `preferredCiphers`, `supportedKexAlgos`, `serverForbiddenKexAlgos`, `preferredKexAlgos`, `supportedHostKeyAlgos`, `supportedMACs`, `hashFuncs`.

Would it rather make sense to configure those per pipe or globally (e.g. in a `downstream_config.yaml`)?

**Comment by tg123** [comment]
no config file yet, but will add them to sshpiperd cmd args

**Comment by Nils98Ar** [comment]
@tg123 Would we rather configure the `supportedPubKeyAuthAlgos` or the `PublicKeyAuthAlgorithms`?

**Comment by Nils98Ar** [comment]
> no config file yet, but will add them to sshpiperd cmd args

We still need to configure the crypto parameters like key exchange algorithm, auth algorithms, ciphers, signature algorith.

Might it be possible to add cmd args for those?

**Comment by tg123** [comment]
yes i will add it soon
