### ISSUE TITLE
LoginGraceTime or equivalent?

### ISSUE THREAD

**Issue by ribatugo** [tg123/sshpiper#39]
Is there any way in 'sshpiperd' to specify something like 'LoginGraceTime' (or other timeouts) as in 'sshd'?
We often encounter dos-like attacks when users from eastern IPs just having fun e.g. by 'telnet our.sshpiper.server 22'.
In such cases 'sshpiperd' does never timeout or drop the connection. So after a short time our ssh proxy is out of free slots.
Are there any plans to support something like 'LoginGraceTime'?

**Comment by tg123** [comment]
Thanks this is very important

359fa095 
added option 
```
--login-grace-time= 
Piper disconnects after this time if the pipe has not successfully established (default: 30s) [$SSHPIPERD_LOGIN_GRACETIME]
```


please test if you have time

**Comment by ribatugo** [comment]
Thanks for such a fast fix!
A quick test by my own says that it is working. Let me see over the weekend what the bad internet is saying to this change...

BTW: A totally fresh installation by 'go get -u github.com/tg123/sshpiper/sshpiperd' says:
# github.com/tg123/sshpiper/sshpiperd/challenger
go/src/github.com/tg123/sshpiper/sshpiperd/challenger/provider.go:12:84: undefined: ssh.AdditionalChallengeContext
# github.com/tg123/sshpiper/sshpiperd/upstream
go/src/github.com/tg123/sshpiper/sshpiperd/upstream/provider.go:17:59: undefined: ssh.AdditionalChallengeContext
go/src/github.com/tg123/sshpiper/sshpiperd/upstream/provider.go:17:103: undefined: ssh.AuthPipe

**Comment by tg123** [comment]
Please use Go1.12+
