### ISSUE TITLE
nothing happening on server

### ISSUE THREAD

**Issue by abhinav-harness** [tg123/sshpiper#420]
I have been trying to use fixed ssh with public key aith and modified the fixed plugin a bit 
```
//go:build full || e2e

package main

import (
	log "github.com/sirupsen/logrus"
	"github.com/tg123/sshpiper/libplugin"
	"github.com/urfave/cli/v2"
)

func main() {

	libplugin.CreateAndRunPluginTemplate(&libplugin.PluginTemplate{
		Name:  "fixed",
		Usage: "sshpiperd fixed plugin, only password auth is supported",
		Flags: []cli.Flag{
			&cli.StringFlag{
				Name:     "target",
				Usage:    "target ssh endpoint address",
				EnvVars:  []string{"SSHPIPERD_FIXED_TARGET"},
				Required: true,
			},
		},
		CreateConfig: func(c *cli.Context) (*libplugin.SshPiperPluginConfig, error) {
			target := c.String("target")
			host, port, err := libplugin.SplitHostPortForSSH(target)
			if err != nil {
				return nil, err
			}

			return &libplugin.SshPiperPluginConfig{
				PublicKeyCallback: func(conn libplugin.ConnMetadata, key []byte) (*libplugin.Upstream, error) {
					log.Info("routing to ", target)
					log.Info("username = ", conn.User())
					log.Infof("Attempting to route connection to target: %s", target)
					log.Infof("Connection metadata: User=%s, ClientVersion=%s, ServerVersion=%s", conn.User(), conn.UniqueID(), conn.RemoteAddr())
					log.Infof("Public Key Length: %d bytes", len(key))
					return &libplugin.Upstream{
						Host:          host,
						Port:          int32(port),
						UserName:      conn.User(),
						Auth:          libplugin.CreatePrivateKeyAuth(key),
						IgnoreHostKey: true,
					}, nil
				},
			}, nil
		},
	})
}
```

Logs on sshpiper
```DEBU[0011] downstream [::1]:61470 (username [git]) is sending public key auth 
INFO[0011] Attempting to route connection to target: localhost:22 
INFO[0011] Connection metadata: User=git, UniqueID=a630c5e6-589b-4fb0-bc92-bef97a06d8ba, RemoteAddr=[::1]:61470 
INFO[0011] Public Key Length: 407 bytes                 
ERRO[0011] cannot create upstream for [::1]:61470 (username [git]) with public key auth: ssh: no key found 
DEBU[0011] connection from [::1]:61470 establishing failed reason: [ssh: no auth passed yet, ssh: no key found, ssh: no key found] 

```

I don't see anything on server and when I quit sshpiper i see following on server 
`read tcp [::1]:22->[::1]:61472: read: connection reset by peer`

**Comment by tg123** [comment]
you are creating a private key using a public key

please check why public key cant be proxy
https://github.com/tg123/sshpiper?tab=readme-ov-file#public-key-authentication-when-using-sshpiper-private-key-remapping

**Comment by abhinav-harness** [comment]
I was able to resolve it - but since we are using a new key - i had information in my old key which is getting lost to map user on upstream. Any way I can send an env variable(i assume that's the best way) to send user information while creating piper?

**Comment by tg123** [comment]
auth happens before sending env vars
i did not get what is missing

the `key` should have everything in public key, you can map it to the new key.
if you are looking for cert, it is the 2nd param to `CreatePrivateKeyAuth(key, cert)`

**Comment by abhinav-harness** [comment]
Downstream sends a public key PK_X and that on piper maps to PK_Y for upstream. 
On piper with PK_X I get some extra info about user (not user name but other information which this public key is tied to), I want to send this information to upstream (probably via env variable) but I am not able to achieve it - Any code pointer would be helpful

**Comment by tg123** [comment]
you cant send env var during auth.
could you please elaborate what info you are going to send to server? how did you do it using raw sshd?

if it is something inside the key, you can generate the new privatekey with those info on the fly inside `PublicKeyCallback`

**Comment by abhinav-harness** [comment]
my upstream had a way to authenticate key and retrieve user information from it for further authorization - with piper in middle i can authenticate using PK_Y and PK_X on piper and get same information but i need to pass that extra user information during either auth or subsequent requests to make it work on upstream. 
Any pointer to code to make it work is appreciated

**Comment by tg123** [comment]
my upstream had `a way` to authenticate key and retrieve user information from it for further authorization
what is `a way` here

with piper in middle i can authenticate using PK_Y and PK_X on piper and get `same information`
what is `same information`

i need to pass `that extra user information` during either auth or subsequent requests to make it work on upstream.
you could convert `that extra user information` to `same information` and pass it to `a way` with newly generated PRIVATE_KEY

**Comment by abhinav-harness** [comment]
we stored in db the user and fingerprint association. 
Once user did ssh during auth we saw the key and also if the association if registered with us, if yes we used to keep this information in session and used it. 

Since a new private key is now coming up we loose that information on piper and want to send that information to upstream via env variable.

**Comment by tg123** [comment]
what about

insert new generated key's fingerprint to db and associate with user info

basically, it looks like the user end put multiple key in your db, and your upstream will still see the linked user from piper's new key
