### ISSUE TITLE
Feature request: support of SSH tunnels

### ISSUE THREAD

**Issue by DClabaut** [tg123/sshpiper#44]
Is there a way to get SSHPiper to act as a reverse-proxy for ssh tunnels, such as those created with Autossh (https://hobo.house/2016/06/20/fun-and-profit-with-reverse-ssh-tunnels-and-autossh/)?
Thanks

**Comment by tg123** [comment]
sshpiper supports `ssh tunnels` including created by autossh

**Comment by DClabaut** [comment]
Indeed, it looks that my issue is with systemd unit files, running autossh manually works.
