### ISSUE TITLE
Can we do password authentication automatically through sshpiper?

### ISSUE THREAD

**Issue by geooid** [tg123/sshpiper#45]
Can we do password authentication automatically through sshpiper?

EG:

We are not using public key, but saved in some file.
Can we input this password automatically fr upstream authentication?

**Comment by tg123** [comment]
for sure, try mysql as upstream.

**Comment by geooid** [comment]
Hi Boshi Lian,

Thanks for the quick update.

Actually we already used file system in our sshpiper environment. is there any option in file type method to input password automatically?

Thanks again for this wonderful piece of software :)

**Comment by tg123** [comment]
not implement yet :(

**Comment by geooid** [comment]
Oh okay. Thanks for the update.

I am currently working on implement it by customising code, do you have any inputs how to do it

Can we simply write password to upstream during authentication?

**Comment by tg123** [comment]
here is how to map anything to password
https://github.com/tg123/sshpiper/blob/master/sshpiperd/challenger/pome/upstream.go#L45

**Comment by geooid** [comment]
Thanks a lot friend :)
