### ISSUE TITLE
Support for certificate based authentication

### ISSUE THREAD

**Issue by carlo-quinonez** [tg123/sshpiper#452]
I searched and saw some issues and even a PR that were relevant to certificate support, but it wasn't clear what plugin supports this nor how to configure it.

Our company has setup [Step CA to enable certificate-based SSH access](https://smallstep.com/docs/ssh/how-it-works/) for service persons supporting customers with the devices we sell.

Does ssh-piper support [certificate-based SSH authentication](https://en.wikibooks.org/wiki/OpenSSH/Cookbook/Certificate-based_Authentication)?

**Comment by tg123** [comment]
yes both downstream and upstream 

but need a customized plugin to do the ca verification 

auth downstream in your case only right?

**Comment by tg123** [comment]
to verify downstream ca, need new custom plugin
to send ca+cert to upstream, you can check exmaple here https://github.com/tg123/sshpiper/blob/master/plugin/testcaplugin/main.go

**Comment by carlo-quinonez** [comment]
Yes, we only need to use certificate authentication of the user that's initiating the ssh connection.

And just want to confirm my understanding...
> Downstream means User -> ssh-piper
> Upstream meand ssh-piper -> device

**Comment by tg123** [comment]
correct 

may i know which plugin you're using, i can add ca check support

**Comment by carlo-quinonez** [comment]
At the moment, we're (re)planning out a solution.

### full context

We designed, implemented and tested a solution based on ssh-piper V0, but project lost momentum and we never deployed it to production. The entire solution consisted of ssh-piper and AWS Step Functions to orchestrate transient jump hosts. The lifecycle of the jump host was tied to the lifecycle of the support case.

The solution involved two instances of ssh-piper, one to handle routing connections from our field service engineerings, and the second instance handled routing connections from the devices. We needed two instances of ssh-piper because people and machines needed to authenticate differently...

Now, we've been asked to resurrect the solution AND enhance it to support certificate based authentication and I'm trying to wrap my head around what, if any, changes we need to make to the prior solution.

**Comment by carlo-quinonez** [comment]
We were using the old database plugin

**Comment by tg123** [comment]
i would suggest to take a look at https://github.com/tg123/sshpiper-openpubkey 
it integrates with google oauth with magic from open public key

also, CA support will be first added to `yaml` plugin soon

**Comment by tg123** [comment]
k8s and yaml now supports ca
