### ISSUE TITLE
To print some messages to downstream before login to the upstream

### ISSUE THREAD

**Issue by geooid** [tg123/sshpiper#46]
Hi Team,

Just want to know how we can print some messages in downstream  before login to the upstream.

I can not use welcome challenges, as my ssh client(gucamole) does not support keyboard interactive method.

I tried below option but seems not working

```
bannerMsg := &userAuthSuccessMsg {
	Reason: 4,
        Message:  "Banner test msg",
}

err := d.transport.writePacket(Marshal(bannerMsg))
```

It seems not working.

Can you please provide any input for it, that will be great help for me.

Thanks again for your great software.

**Comment by tg123** [comment]
Did you try BannerText option?

https://github.com/tg123/sshpiper/blob/a34bf6435a67cf82fb6dcd8f97c608064d910a91/sshpiperd/sshpiperd.go#L29

it is built in with piper

**Comment by geooid** [comment]
Thanks for quick reply.

Can we changed it dynamically according to some conditions?

Also i using very old version of sshpiper - v0.2

Is there any option available with d.transport.writePacket() function?

Thanks for your support.

**Comment by tg123** [comment]
`d.transport.writePacket()` is a low level func.  not going to expose
the message is a dynamic callback
have a look at banner callback https://github.com/tg123/sshpiper/blob/a34bf6435a67cf82fb6dcd8f97c608064d910a91/sshpiperd/sshpiperd.go#L170

**Comment by geooid** [comment]
Thanks for the input, I have gone through the  golang.org/x/crypto/ssh/server.go file and found following sample code.

```
type userAuthBannerMsg struct {
	Message string `sshtype:"53"`
	// unused, but required to allow message parsing
	Language string
}

bannerMsg := &userAuthBannerMsg{
	Message: "Banner test msg",
}

err := d.transport.writePacket(Marshal(bannerMsg))
```

That worked for me.

Thanks again for your great support friend :)

**Comment by tg123** [comment]
nice to know

sshpiper fork here
https://github.com/tg123/sshpiper.crypto

**Comment by geooid** [comment]
Thanks Boshi. I will follow it.
