### ISSUE TITLE
Is the `database` routing plugin supported in v1?

### ISSUE THREAD

**Issue by carlo-quinonez** [tg123/sshpiper#462]
We have an project using ssh-piper v0 that uses the [databases routing plugin](https://github.com/tg123/sshpiper/tree/v0/sshpiperd/upstream/database).

Is the database plugin still supported?

**Comment by tg123** [comment]
is it possible to migrate to kubernetes plugin?

kubectl and kubeapi works better than database

**Comment by tg123** [comment]
hi @carlo-quinonez 
port https://github.com/tg123/sshpiper-plugins/tree/main/database to v1

the code is not fully tested, will add testcase later, please let me if this works

**Comment by tg123** [comment]
testcase passed, database plugin is now good with v1

**Comment by carlo-quinonez** [comment]
@tg123 I'll test and make a PR for the docs. Is the tunnel management API/CLI same as v0?

**Comment by tg123** [comment]
a little change to the schema, 
removed some unsupported field

you can find code to create routing
https://github.com/tg123/sshpiper-plugins/blob/4f69c56fcdf55d630d0ea28bc859093641671e49/database/e2e_test.go#L248C1-L269C4

detail diff here
https://github.com/tg123/sshpiper-plugins/commit/8c630546cff60968f106401b5166bfb5f27fabb4#diff-bb1fbea522d7baea1edd74762a89b1445d3f71e032b199d1c5a833413224baa7
