### ISSUE TITLE
Is it possible to allow passthrough of authentication?

### ISSUE THREAD

**Issue by ShadowFox88** [tg123/sshpiper#480]
I have an instance of gitlab I'm looking to put behind this, with git@example.com routing to that port on an external machine, with my username routing to my local machine's ssh. Would it be possible to set this up such that when I authenticate, rather than sshpiper connecting to gitlab with its own key, it uses mine, rather than me having to provide that key to the sshpiper instance?

**Comment by ShadowFox88** [comment]
Never mind, realised my mistake.

**Comment by OIRNOIR** [comment]
> Never mind, realised my mistake.

What did you find? I'm stuck on the same issue, I feel. My hope is to be able to use sshpiper to proxy only the `git` user transparently (passing through auth) and deny all other login requests, but I'm unsure of how this can be done.

**Comment by tg123** [comment]
there is no way to passthrough the key-based auth, but you can do password if you think it is ok

**Comment by OIRNOIR** [comment]
> there is no way to passthrough the key-based auth, but you can do password if you think it is ok

Thank you for answering! sshpiper isn't the right tool for my problem, then, but it's still a really cool program :)

**Comment by ShadowFox88** [comment]
Yeah, I I ended up just having gitlab on port 22 and having ssh on port 23.
