### ISSUE TITLE
Session logging

### ISSUE THREAD

**Issue by archongtv** [tg123/sshpiper#5]
It would be nice, if sshpiper has session logging to file / syslog.

**Comment by tg123** [comment]
session logging = all input and output?

**Comment by archongtv** [comment]
Yes, it would act as kind of proxy and auditing tool for ops connecting to servers (to see who did what).

**Comment by tg123** [comment]
yes, there is.
but not included in opensource version of sshpiper at the time

**Comment by archongtv** [comment]
So where I can find non open source version? ;)

**Comment by tg123** [comment]
opensourced
