### ISSUE TITLE
Security question

### ISSUE THREAD

**Issue by TomFreudenberg** [tg123/sshpiper#53]
Hi,

first of all thanks for your effort on SSHPIPER

We have made some first steps and it worked so far.

But I am wondering about the current security status.

How do you compare SSHPIPERD liability to OPENSSH?

Is SSHPIPER able and safe to be used as a front-end system?

Do you know some kind of vulnary issues when using in a data center?

Is it as safe as using an OPENSSH port?

Thanks for some clarification and feedback.

Cheers
Tom

**Comment by TomFreudenberg** [comment]
Hi @tg123 

Maybe you are also interested in this thread on OpnSense

https://forum.opnsense.org/index.php?topic=18894.0

**Comment by tg123** [comment]
sshpiper depends on a modified version of golang.org/crypto <https://github.com/tg123/sshpiper.crypto>
i do not have data of `liability` of sshpiper. openssh has been running for years, but sshpiper is pretty new anyway.

the sshpiper is designed to use as the front-end system. so you may want to put it in between lb and backend ssh servers

i know some startups were using sshpiper or its derive product. but i have no access to any of their security data.

**Comment by TomFreudenberg** [comment]
Thanks @tg123 

When looking at https://github.com/golang/crypto/compare/master...tg123:master

there are new commits on golang crypto. Will you merge that too and keep the sshpiper.crypto up-to-date in future?

**Comment by tg123** [comment]
Yes for sure
