### ISSUE TITLE
Graceful shutdown/hot reload

### ISSUE THREAD

**Issue by robertgates55** [tg123/sshpiper#55]
Is there any way to 'reload' sshpiper with a new pipes config? I'm using the yaml upstream_provider.

Alternatively is there a way to shut down sshpiper in such a way that it stops accepting new connections and waits until open sessions are closed?

**Comment by tg123** [comment]
it was planned years ago
but never implemented :(

PR is welcomed

**Comment by robertgates55** [comment]
Cool. We'll have a look. Do you have any rough idea of where we'd be looking to put a change in?

(just asking in case there was already a bit of thought that could point us in the right direction)

**Comment by tg123** [comment]
was thinking to copy/paste idea from nginx
http://nginx.org/en/docs/control.html

the reason it was postponed is that i found ssh sessions would live much longer than http (nginx) ones

**Comment by developedsoftware** [comment]
Wouldnt this be resolved if you used a rest upstream (or some other upstream that fetches data on every connection request)

Is this request only applicable to the workingdir upstream driver?

**Comment by tg123** [comment]
no this is for sshpiperd itself to restart gracefully

**Comment by tg123** [comment]
as v1 plugin was introduced, hot reload is not doable
