### ISSUE TITLE
Install via snap fails on Ubuntu 20.04, 18.04

### ISSUE THREAD

**Issue by freddrueck** [tg123/sshpiper#58]
Hello,

I've been trying to install via the snap on a few different Ubuntu boxes via the snap package.  I get error:

root@lxtester:~# snap install sshpiperd
error: cannot perform the following tasks:
- Run install hook of "sshpiperd" snap if present (run hook "install": /snap/sshpiperd/63/meta/hooks/install: 7: /snap/sshpiperd/63/meta/hooks/install: /snap/sshpiperd/63/sshpiperd: not found)

This boxes has very few snaps installed:

root@lxtester:~# snap list
Name    Version    Rev    Tracking       Publisher   Notes
core    16-2.47.1  10185  latest/stable  canonical*  core
core18  20200929   1932   latest/stable  canonical*  base
lxd     4.8        18402  latest/stable  canonical*  -
snapd   2.47.1     9721   latest/stable  canonical*  snapd

This the box running 18.04 which I happen to be logged into at the moment.  I think the error and installed snaps are identical on the other box running 20.04

**Comment by tg123** [comment]
this is due to libc missing 
remove cgo atm
```
sudo snap install sshpiperd
sshpiperd 0.5.1 from tg123 (farmer1992) installed
```
