### ISSUE TITLE
execessive memory usage when running in production

### ISSUE THREAD

**Issue by jalr** [tg123/sshpiper#59]
I'm using sshpiper in production. After some days, it takes gigabytes of memory.
After adding pprof to sshpiper, I saw one gouroutine waiting in `[chan send]` piling up for every closed ssh session.

I'm not that familiar with golang but I still tried to fix this issue: https://github.com/jalr/sshpiper.crypto/commit/87ea0e0100cbaf99fa65f24eccd7c1c825e83965

**Comment by tg123** [comment]
`c := make(chan error, 2)` would fix it
I will update it and let you try

really appreciate

**Comment by tg123** [comment]
fixed in latest version please check thanks

**Comment by jalr** [comment]
Thanks alot for the fast fix!
