### ISSUE TITLE
Dynamic configuration for docker / swarm containers ?

### ISSUE THREAD

**Issue by pwFoo** [tg123/sshpiper#60]
Hi,
I know it could be done with additional scripts and piper command, but would be nice to have a plugin / integration... Don't know how much work it would be!

It would be great to generate the a sshpiper user by docker container labels as done with [caddy-docker-proxy](https://github.com/lucaslorentz/caddy-docker-proxy). sshpiper would need to read SSHPIPER_* labels (user, pass, pubkey, ...) from docker.sock, collect container or swarm (v)ip and generate the needed sshpiper configuration.

**Comment by tg123** [comment]
sshpiper already supported load from env like SSHPIPER_* 
maybe the only thing is to generate containers with those envs

**Comment by pwFoo** [comment]
Ok, but sshpiper (or docker-gen) need to read other containers ENV via docker.sock. Native way to read docker.sock would be great, but alternative I need to update my sshpiper + docker-gen construct to the actual version of sshpiper

**Comment by pwFoo** [comment]
> sshpiper already supported load from env like SSHPIPER_*
> maybe the only thing is to generate containers with those envs

sshpiper read _**other containers**_ SSHPIPER_* ENV or just the local ENV? Other containers ENV would be awesome to auto config SSHpiper with other container ENV + container ip as upstream.

**Comment by tg123** [comment]
introduced with
https://github.com/tg123/sshpiper/tree/master/plugin/docker

thanks `v1`'s flexibility

**Comment by pwFoo** [comment]
Awesome!!! Tested with gitea ssh behind sshpiper
