### ISSUE TITLE
How do you disable password login

### ISSUE THREAD

**Issue by developedsoftware** [tg123/sshpiper#67]
I am trying to ensure any SSH logins are done via rsa keys. 

I have altered my servers to only allow rsa keys, but I still get presented with a enter password when going through sshpiper. 

I can see in the log - "public key auth failed user XX". 

At this point I want the connection to be terminated by sshpiper rather than prompted to enter a password (to then be rejected by my server)

How would I do this?

**Comment by tg123** [comment]
sshpiper pipes the `next auth methods` from upstream, I think you did not set sshd properly, the entry in `sshd_config` is `PasswordAuthentication no`
run `ssh -v yourupstream` to see if it asks for password

bad example 
`Authentications that can continue: publickey,password`


anyway, I think providing a way to block it from sshpiper is a good idea.

**Comment by developedsoftware** [comment]
Adding the following to /etc/ssh/sshd_config on both sshpiper and my upstream boxes fixed it. Closing.

`AuthenticationMethods publickey`
