### ISSUE TITLE
Only show banner if upstream authentication succeeds

### ISSUE THREAD

**Issue by developedsoftware** [tg123/sshpiper#69]
At the moment it shows regardless if connection to upstream fails or not. 

Is there any reason to show the welcome banner if authentication fails (it may contain information that only valid ssh connections should see - like workflow instructions to developers)

**Comment by tg123** [comment]
this is by design
ref
https://datatracker.ietf.org/doc/html/rfc4252#section-5.4


>   The SSH server may send an SSH_MSG_USERAUTH_BANNER message at any
>  time after this authentication protocol starts and **before
> authentication is successful**.
