### ISSUE TITLE
Using password

### ISSUE THREAD

**Issue by shurco** [tg123/sshpiper#7]
How use password for connect external server ?

**Comment by tg123** [comment]
cloud you please describe your question more clearly?

sshpiper would ask for your password and pass it to real ssh server.

**Comment by shurco** [comment]
> sshpiper would ask for your password and pass it to real ssh server.
how can I send the password automatically?

For example, I have 2 server:
1 server use rsa key (automatically connects)
2 server use only password (I enter the password, but I would like to automate this)

**Comment by tg123** [comment]
this feature is under developing
will give chance to user to modify the auth method to upstream.

sorry for my laziness

**Comment by shurco** [comment]
@tg123 would you release an update in the nearest future?

**Comment by tg123** [comment]
maybe early 2018

**Comment by tg123** [comment]
Hi @shurco 

I have `map publickey to password` added 

here is the testcase and looking way to integrate it with sshpiperd 

https://github.com/tg123/sshpiper/blob/f6c4ae82d452ec1268a56bc1ecece723b7bcd8d6/vendor/golang.org/x/crypto/ssh/sshpiper_test.go#L244

**Comment by alexschomb** [comment]
@tg123 Perfect. Looking forward to this functionality as well. Does that mean that users will be able login via password to sshpiperd that itself authenticates via publickey?

**Comment by tg123** [comment]
@alexschomb yes

but only api level, not export to sshpiperd yet. 
this feature is on the way

**Comment by alexschomb** [comment]
Perfect, I‘ll be patiently waiting. Thank you so much for your great work 👍

**Comment by Rakiah** [comment]
Hey, is this working now ?

It seems like I cant connect using a password

**Comment by tg123** [comment]
@Rakiah 
seems this is something wrong on server side
please see/attach your sshpiper log

connection closed during handshake `ssh_exchange_identification`
you may want to create a new bug for it.
