### ISSUE TITLE
Example config ssh keys with MYSQL driver

### ISSUE THREAD

**Issue by rjbaat** [tg123/sshpiper#70]
Hi All,
I am trying to get the mysql driver to work with sshpiper. But I think I need a bit more help, since is don't get it to work with the current documentation and with ssh keys. The sshpiper container is connected properly to the mysql database. Also it did make the required tables. Also i tried to add a new pipe with adding it via cli.
With the password auth it is actually working, but not with ssh keys.

Is there a way you guys can supply me with a SQL export of working example with some example ssh keys?
And maybe a little explanation of how the tables are related and what the corresponding values mean and should be when it is properly configured?

Thnx in advance.

**Comment by tg123** [comment]
`
./sshpiperd pipe --upstream-driver=mysql add
`

to manage them, i will update key based related examples in coming weeks
