### ISSUE TITLE
Add option to map user from k8s provider

### ISSUE THREAD

**Issue by shiipou** [tg123/sshpiper#74]
I didn't see any option to map user like : `vm01` to `user` in the vm.

I see in #12 that's is possible to configure using cli config so I think that can be done using k8s provider with a `target.remote-user` option or something like this ?

Thanks for this great project, if that cannot be done like this, I'll use the database provider in my project to configure redirection instead.
👍

**Comment by tg123** [comment]
added in https://github.com/tg123/sshpiper/tree/master/plugin/kubernetes
