### ISSUE TITLE
request: kubernetes upstream support public key authentication

### ISSUE THREAD

**Issue by automaticgiant-ml** [tg123/sshpiper#76]
@lermit it looks like this upstream plugin doesnt support public key auth but im not sure.
i think i might need to configure the upstreams with a different plugin, or patch in the functionality.

_Originally posted by @automaticgiant-ml in https://github.com/tg123/sshpiper/issues/66#issuecomment-919932275_

**Comment by automaticgiant-ml** [comment]
@tg123 would you be able to provide any more documentation about the plugin interface, specifically with respect to key exchange and validation between sshpiper and upstreams?
thanks

**Comment by tg123** [comment]
added in https://github.com/tg123/sshpiper/tree/master/plugin/kubernetes
