### ISSUE TITLE
How to connect to host itself automatically?

### ISSUE THREAD

**Issue by mindfuucker** [tg123/sshpiper#78]
My usecase is somewhat different then the examples given:

- I have a VPS with a fixed IP
- I host some services at home and tunnel them through wireguard to the VPS
- sshpiper is running on the VPS in a docker container

Using the docker container and a simple home-like directory `sshpiper_upstream` file I'm able to SSH my homeserver through the wireguard VPN. 

Is sshpiper aware of the already existing users on the VPS? Is there a method to forward/pipe all users without a home-like directory to the host?

**Comment by tg123** [comment]
reopen if cannot do it with grpc
