### ISSUE TITLE
Does `sshpiper` support port forwarding?

### ISSUE THREAD

**Issue by carlo-quinonez** [tg123/sshpiper#83]
First off, awesome tool! A colleague pointed this out to me as a potential solution for one of our projects. It seems ideal, but was wondering if `sshpiper` supports remote and local port forwarding? So would commands like the following work:

```
ssh -L 80:intra.example.com:80 gw.example.com
ssh -R 8080:localhost:80 public.example.com
```

**Comment by tg123** [comment]
yes
sshpiper route raw ssh packages after handshake. file a bug if it is not.

**Comment by carlo-quinonez** [comment]
Thank you. As soon as I confirm, we'll post an update.

**Comment by tg123** [comment]
reopen if any issue for port forward
