### ISSUE TITLE
Add support for log levels

### ISSUE THREAD

**Issue by michael-skiles-tfs** [tg123/sshpiper#85]
First off, thank you for your work on this project!

Currently, there does not appear to be a way to control the log level of the `sshpiper`  daemon, presenting a couple of issues:

1. All start-up configuration, including the username/password for the database driver, are emitted to the logs on start.
2. Every accepted TCP connection is logged, even if it is not a valid SSH connection. This means having to deal with a really polluted log file if you want to configure an external TCP health check to ensure the daemon is up and running.

Having the option to only emit these messages at a `DEBUG` log level would be very useful!

**Comment by tg123** [comment]
hmm totally agree. we have the same compliance issue, as a result, the upstream now is our private grpc version.

the logging driver now does not support it.
I am going to replace it and make log level available
