### ISSUE TITLE
Possible to configure challenger-driver by pipe?

### ISSUE THREAD

**Issue by michael-skiles-tfs** [tg123/sshpiper#86]
Hello @tg123!

I know it's possible to configure different upstream drivers when adding a new pipe, and was wondering if challenges and be configured the same way. For example:

`/sshpiperd --challenger-driver=azdevcode pipe add ...`

Thanks!

**Comment by tg123** [comment]
challenger is a global setting for now
i am adding challenger api to grpc upstream, thus, you can have per pipe challenger

**Comment by tg123** [comment]
the figure is now doable by introducing `v1`
need to create a new plugin to do different challenger by pipe

let me know your detailed scenario and I will see how I can help

**Comment by Damme** [comment]
I would be interested in this, I still use the workingdir router and an extra file for example totp.key with the secret and no or empty file equals no totp for this route.
Similar technique for the other router, being able to specify secret or no totp per route (user).

**Comment by tg123** [comment]
@Damme 
This is technically doable, but could you please elaborate your scenario or how do you think the config is like
Maybe a customized plugin or something i can make it global

**Comment by 11notes** [comment]
IMHO it would be enough if we could enable a challenge driver by route, ie YAML:

`version: "1.0"
pipes:
- from:
    - username: "sshpiperd"
      authorized_keys: /sshpiperd/var/sshpiperd/authorized_keys
      challenges:
        - totp
        - simplemath
  to:
    host: 192.168.255.1:22
    username: "sshpiperd"
    private_key: /sshpiperd/var/sshpiperd/id_rsa
    ignore_hostkey: true`

like this you could enable multiple challenges per route which have to be completed in succession.

**Comment by 11notes** [comment]
> Hello @tg123!
> 
> I know it's possible to configure different upstream drivers when adding a new pipe, and was wondering if challenges and be configured the same way. For example:
> 
> `/sshpiperd --challenger-driver=azdevcode pipe add ...`
> 
> Thanks!
@michael-skiles-tfs (@tg123)
I have created a plugin that can almost do that, it can skip the challenge or not, depending on your backend, it's a rest plugin so it works with anything: https://github.com/11notes/docker-sshpiper

**Comment by tg123** [comment]
> > Hello @tg123!
> > I know it's possible to configure different upstream drivers when adding a new pipe, and was wondering if challenges and be configured the same way. For example:
> > `/sshpiperd --challenger-driver=azdevcode pipe add ...`
> > Thanks!
> > @michael-skiles-tfs (@tg123)
> > I have created a plugin that can almost do that, it can skip the challenge or not, depending on your backend, it's a rest plugin so it works with anything: https://github.com/11notes/docker-sshpiper

can i link your plugin to readme? or you can send a PR as well

**Comment by 11notes** [comment]
> > > Hello @tg123!
> > > I know it's possible to configure different upstream drivers when adding a new pipe, and was wondering if challenges and be configured the same way. For example:
> > > `/sshpiperd --challenger-driver=azdevcode pipe add ...`
> > > Thanks!
> > > @michael-skiles-tfs (@tg123)
> > > I have created a plugin that can almost do that, it can skip the challenge or not, depending on your backend, it's a rest plugin so it works with anything: https://github.com/11notes/docker-sshpiper
> 
> can i link your plugin to readme? or you can send a PR as well

added PR https://github.com/tg123/sshpiper/pull/159
