### ISSUE TITLE
Log username from additional Challenger

### ISSUE THREAD

**Issue by carlo-quinonez** [tg123/sshpiper#88]
When using the AzureAD Challenger, the user name is not being logged.

**Comment by tg123** [comment]
thanks for your kindness

logs related to upstream and challenger improved in 7639c1d5a7dc5352c77e7cb12716a4bc5e0ca60f

```
INFO[0025] challenger [azdevicecode] success with challenged username [11111111-1111-1111-1111-111111111111]
```

where the guid is azure's account id

**Comment by michael-skiles-tfs** [comment]
Confirmed the updated handler works with the Microsoft Graph API, and that the correct user GUID is getting logged as expected. I'm very impressed and thankful for the amazing support you've been providing on this project @tg123!
