### ISSUE TITLE
[feature request] route connections by destination server

### ISSUE THREAD

**Issue by shadu120** [tg123/sshpiper#90]
some times we want to use a trasparent ssh proxy for specified ssh host request in enterprise enviroment.

Server-A.com and Server-B.com are mapping to the same destination.

![image](https://user-images.githubusercontent.com/3023471/172029234-5b6a1fbf-53f1-4f3e-9256-b781754bb0a9.png)

**Comment by shadu120** [comment]
Because SSH session does not contain any server name,  I don't think sshpiper can solve this.

This is the best solution for me till now: https://www.haproxy.com/blog/route-ssh-connections-with-haproxy/

I'm seeking new solutions...

**Comment by tg123** [comment]
#72
