### ISSUE TITLE
Feature request: Caddy layer4 package integration

### ISSUE THREAD

**Issue by rmmanseau** [tg123/sshpiper#98]
heyo, I mentioned this package in an issue for the caddy webservers layer 4 plugin, https://github.com/mholt/caddy-l4/issues/63

Its goal is to allow reverse proxying of raw TCP/UDP connections including SSH, but currently doesn't support matching against SSH username. You're package already supports that so I was wondering if some sort of integration between the two projects was possible. the caddy author sounds interested, so I figured I would post an issue here as well to see what you think !

**Comment by tg123** [comment]
close
caddy might take sshpiper as a lib

let me know if anything i can help
